name = "MyExample2"
uuid = "0f019aec-2a28-4104-895b-325b8d182301"
authors = ["Abhishek Bhatt"]
version = "0.1.0"

[compat]
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
